# coding: utf-8

user1 = User.create(nickname: '仮太郎', email: 'test1@gmail.com', password: 12345678, phone_number: 1122223333)
User.create(nickname: '金太郎', email: 'test2@gmail.com', password: 12345678, phone_number: 1111111111)
User.create(nickname: '子太郎', email: 'test3@gmail.com', password: 12345678, phone_number: 1122222222)
User.create(nickname: '花子', email: 'test4@gmail.com', password: 12345678, phone_number: 1133333333)
User.create(nickname: '菊子', email: 'test5@gmail.com', password: 12345678, phone_number: 1144444444)
User.create(nickname: '幸子', email: 'test6@gmail.com', password: 12345678, phone_number: 1155555555)
Profile.create(user_id: 1, first_name: '仮', last_name: '太郎', first_name_katakana: 'カリ', last_name_katakana: 'タロウ', birthday: 20000101, postal_code: 1112222, prefecture: 1, city: '名古屋市', address: '栄4-5', building: "", introduction: 'こんにちは', avatar: 'https://pbs.twimg.com/profile_images/1068067146201149441/mdA4ZSRj_400x400.jpg', point: 200)
Profile.create(user_id: 2, first_name: '金', last_name: '太郎', first_name_katakana: 'キン', last_name_katakana: 'タロウ', birthday: 20000101, postal_code: 1112222, prefecture: 7, city: '松本市', address: '松本城', building: "天守閣", introduction: 'こんにちは', avatar: 'https://stat.ameba.jp/user_images/20190114/14/hiackl-4/25/57/p/o0320024014338711118.png?caw=800', point: 0)
Profile.create(user_id: 3, first_name: '子', last_name: '太郎', first_name_katakana: 'コ', last_name_katakana: 'タロウ', birthday: 20000101, postal_code: 1112222, prefecture: 31, city: '熊本市', address: '熊本城', building: "正門守衛室", introduction: 'こんにちは', avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTx2ZdpsC676bWEko3mavn7HnqPlVHtJvxzERaq6GKFSgUoRaUbWQ', point: 50)
Profile.create(user_id: 4, first_name: '花', last_name: '子', first_name_katakana: 'ハナ', last_name_katakana: 'コ', birthday: 20000101, postal_code: 1112222, prefecture: 15, city: '那覇市', address: '首里城', building: "駐車場", introduction: 'こんにちは', avatar: 'https://appmedia.jp/wp-content/uploads/2017/04/62e15f764088afdec8cca5ad44ede73a.jpg', point: 1000)
Profile.create(user_id: 5, first_name: '菊', last_name: '子', first_name_katakana: 'キク', last_name_katakana: 'コ', birthday: 20000101, postal_code: 1112222, prefecture: 7, city: '弘前市', address: '弘前城', building: "客間", introduction: 'こんにちは', avatar: 'https://gamewith.akamaized.net/article/thumbnail/rectangle/36550.png', point: 150)
Profile.create(user_id: 6, first_name: '幸', last_name: '子', first_name_katakana: 'サチ', last_name_katakana: 'コ', birthday: 20000101, postal_code: 1112222, prefecture: 22, city: '姫路市', address: '姫路城', building: "中央広場", introduction: 'こんにちは', avatar: 'https://images-fe.ssl-images-amazon.com/images/I/41PMAH6kJGL._SX300_QL70_.jpg', point: 0)
Addressee.create(user_id: 1, first_name: '仮', last_name: '太郎', first_name_katakana: 'カリ', last_name_katakana: 'タロウ', postal_code: 1112222, prefecture: 1, city: '名古屋市', address: '栄4-5', building: "中日ビル", phonenumber: 1111111111)
Addressee.create(user_id: 2, first_name: '金', last_name: '太郎', first_name_katakana: 'キン', last_name_katakana: 'タロウ', postal_code: 1112222, prefecture: 7, city: '松本市', address: '松本城', building: "天守閣", phonenumber: 1122222222)
Addressee.create(user_id: 3, first_name: '子', last_name: '太郎', first_name_katakana: 'コ', last_name_katakana: 'タロウ', postal_code: 1112222, prefecture: 31, city: '熊本市', address: '熊本城', building: "正門守衛室", phonenumber: 1133333333)
Addressee.create(user_id: 4, first_name: '花', last_name: '子', first_name_katakana: 'ハナ', last_name_katakana: 'コ', postal_code: 1112222, prefecture: 15, city: '那覇市', address: '首里城', building: "駐車場", phonenumber: 1144444444)
Addressee.create(user_id: 5, first_name: '菊', last_name: '子', first_name_katakana: 'キク', last_name_katakana: 'コ', postal_code: 1112222, prefecture: 7, city: '弘前市', address: '弘前城', building: "客間", phonenumber: 1155555555)
Addressee.create(user_id: 6, first_name: '幸', last_name: '子', first_name_katakana: 'サチ', last_name_katakana: 'コ', postal_code: 1112222, prefecture: 22, city: '姫路市', address: '姫路城', building: "中央広場", phonenumber: 1166666666)
lady = Category.create(category_name: "レディース")
men = Category.create(category_name: "メンズ")
kids = Category.create(category_name: "ベビー・キッズ")
Category.create(category_name: "インテリア・住まい・小物")
Category.create(category_name: "本・音楽・ゲーム")
Category.create(category_name: "コスメ・香水・美容")
Category.create(category_name: "家電・スマホ・カメラ")
Category.create(category_name: "スポーツ・レジャー")
Category.create(category_name: "ハンドメイド")
Category.create(category_name: "チケット")
Category.create(category_name: "自動車・オートバイ")
Category.create(category_name: "その他")
lady_tops = lady.children.create(category_name: "トップス")
lady_outer = lady.children.create(category_name: "ジャケット/アウター")
lady_pants = lady.children.create(category_name: "パンツ")
lady_scart = lady.children.create(category_name: "スカート")
lady_onepeace = lady.children.create(category_name: "ワンピース")
lady_shoes = lady.children.create(category_name: "靴")
lady_bag = lady.children.create(category_name: "バッグ")
lady_acce = lady.children.create(category_name: "アクセサリー")
lady_komono = lady.children.create(category_name: "小物")
lady_other = lady.children.create(category_name: "その他")
lady_t_shirt = lady_tops.children.create(category_name: "Tシャツ/カットソー(七分/長袖)")
lady_t_shirt2 = lady_tops.children.create(category_name: "Tシャツ/カットソー(半袖/袖なし)")
lady_shirt = lady_tops.children.create(category_name: "シャツ/ブラウス(七分/長袖)")
lady_shirt2 = lady_tops.children.create(category_name: "シャツ/ブラウス(七分/長袖)")
lady_poro_shirt = lady_tops.children.create(category_name: "ポロシャツ")
lady_nit = lady_tops.children.create(category_name: "ニット/セーター")
lady_parkar = lady_tops.children.create(category_name: "パーカー")
lady_jersey = lady_tops.children.create(category_name: "ジャージ")
lady_other = lady_tops.children.create(category_name: "その他")
lady_t_jacket = lady_outer.children.create(category_name: "テーラードジャケット")
lady_n_jacket = lady_outer.children.create(category_name: "ノーカラージャケット")
lady_g_jacket = lady_outer.children.create(category_name: "Gジャン/デニムジャケット")
lady_l_jacket = lady_outer.children.create(category_name: "レザージャケット")
lady_coat = lady_outer.children.create(category_name: "コート")
lady_outer_other = lady_outer.children.create(category_name: "その他")
lady_d_pant = lady_pants.children.create(category_name: "デニム")
lady_s_pant = lady_pants.children.create(category_name: "ショートパンツ")
lady_w_pant = lady_pants.children.create(category_name: "ワークパンツ")
lady_c_pant = lady_pants.children.create(category_name: "チノパン")
lady_o_pant = lady_pants.children.create(category_name: "オーバーオール")
lady_pant_other = lady_pants.children.create(category_name: "その他")
lady_m_scart = lady_scart.children.create(category_name: "ミニスカート")
lady_h_scart = lady_scart.children.create(category_name: "ひざ丈スカート")
lady_l_scart = lady_scart.children.create(category_name: "ロングスカート")
lady_k_scart = lady_scart.children.create(category_name: "キュロット")
lady_scart_other = lady_scart.children.create(category_name: "その他")
lady_m_onepeace = lady_onepeace.children.create(category_name: "ミニワンピース")
lady_h_onepeace = lady_onepeace.children.create(category_name: "ひざ丈ワンピース")
lady_l_onepeace = lady_onepeace.children.create(category_name: "ロングワンピース")
lady_onepeace_other = lady_onepeace.children.create(category_name: "その他")
lady_h_shoes = lady_shoes.children.create(category_name: "ハイヒール/パンプス")
lady_b_shoes = lady_shoes.children.create(category_name: "ブーツ")
lady_s_shoes = lady_shoes.children.create(category_name: "スニーカー")
lady_sn_shoes = lady_shoes.children.create(category_name: "サンダル")
lady_shoes_other = lady_shoes.children.create(category_name: "その他")
lady_h_bag = lady_bag.children.create(category_name: "ハンドバック")
lady_t_bag = lady_bag.children.create(category_name: "トートバック")
lady_b_bag = lady_bag.children.create(category_name: "ボストンバック")
lady_r_bag = lady_bag.children.create(category_name: "リュックサック")
lady_bag_other = lady_bag.children.create(category_name: "その他")
lady_n_acce = lady_acce.children.create(category_name: "ネックレス")
lady_b_acce = lady_acce.children.create(category_name: "ブレスレット")
lady_p_acce = lady_acce.children.create(category_name: "ピアス")
lady_e_acce = lady_acce.children.create(category_name: "イヤリング")
lady_acce_other = lady_acce.children.create(category_name: "その他")
lady_n_komono = lady_komono.children.create(category_name: "長財布")
lady_o_komono = lady_komono.children.create(category_name: "折りたたみ財布")
lady_c_komono = lady_komono.children.create(category_name: "コインケース")
lady_komono_other = lady_komono.children.create(category_name: "その他")
Brand.create(category_id: lady_t_shirt.id, brand_name: "ナイキ")